name: RequestTimeout Repository Policy

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test script
        env:
          ADMIN_PAT: ${{ secrets.ADMIN_PAT }}
        run: |
          python scripts/check_repo.py
          CODE=$?
          echo "PYTHON EXIT CODE = $CODE"
          exit 0
