name: RequestTimeout Repository Policy

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python scripts/check_repo.py > output.log 2>&1 || true
          cat output.log
